# Generated by Django 6.0.6 on 2026-06-12 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours'), ('TRAITE', 'Traité')], default='BROUILLON', max_length=20)),
                ('decision', models.CharField(blank=True, choices=[('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée')], max_length=20, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('traite_at', models.DateTimeField(blank=True, null=True)),
                ('last_relance_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='demandes.demande')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('PROJET', 'Projet (distributeur)'), ('DEFINITIVE', 'Définitive (siège)')], default='PROJET', max_length=20)),
                ('validee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='demandes.demande')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('COHERENT', 'Cohérent'), ('INCOHERENCES', 'Incohérences détectées')], max_length=20)),
                ('incoherences', models.JSONField(default=list)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse_ia', to='demandes.demande')),
            ],
        ),
        migrations.CreateModel(
            name='FDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assure_nom', models.CharField(blank=True, max_length=255, verbose_name='Nom / raison sociale')),
                ('assure_ville', models.CharField(blank=True, max_length=255)),
                ('assure_numero_contrat', models.CharField(blank=True, max_length=100)),
                ('chantier_nom', models.CharField(blank=True, max_length=255)),
                ('chantier_ville', models.CharField(blank=True, max_length=255)),
                ('chantier_type', models.CharField(blank=True, choices=[('NEUVE', 'Construction neuve'), ('RENOVATION', 'Rénovation')], max_length=20)),
                ('modification_structure', models.BooleanField(default=False)),
                ('usage', models.CharField(blank=True, choices=[('HABITATION', 'Habitation'), ('BUREAU', 'Bureau'), ('COMMERCE', 'Commerce'), ('AUTRE', 'Autre')], max_length=20)),
                ('usage_autre_texte', models.CharField(blank=True, max_length=255)),
                ('chantier_atypique', models.BooleanField(default=False)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('cout_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('description_travaux', models.TextField(blank=True)),
                ('montant_prestation', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('type_intervention', models.CharField(blank=True, choices=[('ENTREPRISE_PRINCIPALE', 'Entreprise principale'), ('SOUS_TRAITANT', 'Sous-traitant')], max_length=30)),
                ('activite_couverte', models.BooleanField(default=True)),
                ('activite_couverte_texte', models.TextField(blank=True)),
                ('travaux_standards', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fdr', to='demandes.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='demandes.demande')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='pieces/%Y/%m/')),
                ('nom_original', models.CharField(blank=True, max_length=255)),
                ('type_requis', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='demandes.demande')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
