# Generated by Django 6.0.6 on 2026-06-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='complement_champs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='demande',
            name='complement_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
