# Generated by Django 6.0.6 on 2026-06-16 15:00

import demandes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_demande_complement_champs_demande_complement_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piecejustificative',
            name='fichier',
            field=models.FileField(upload_to='pieces/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), demandes.models.validate_piece_size]),
        ),
    ]
